#!/usr/bin/env python3

"""
Get the temperature of the primary CPU thermal zone, in celsius.
"""


from argparse import ArgumentParser
from inspect import getdoc
from pathlib import Path
from sys import modules


ArgumentParser(description=getdoc(modules[__name__])).parse_args()

paths = frozenset(
    {
        Path(p)
        for p in {
            "/sys/class/thermal/thermal_zone0/temp",
            "/sys/class/hwmon/hwmon0/temp1_input",
        }
    }
)

path = next((p for p in paths if p.is_file()), None)
if not path:
    paths_msg = " or ".join(str(p) for p in paths)
    raise RuntimeError(
        f"Error: temperature paths {paths_msg} not found; are you "
        "running outside of Linux or inside a container?"
    )

content = path.read_text().strip()
celsius = int(content) if len(content) < 4 else int(content) / 1000

print(f"{celsius}C")
